// <auto-generated />
namespace GuessResult.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createNewTableFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createNewTableFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041702037_createNewTabl;eFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
